package org.springframework.roo.addon.finder.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks the annotated type as a Spring Data JPA repository that 
 * contains finders generated by Spring Roo. 
 * 
 * @author Juan Carlos García
 * @since 2.0
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface RooFinder {

  /**
   * The name of this annotation's attribute that specifies the finders
   */
  String FINDERS_ATTRIBUTE = "finders";


  /**
   * The String array of finder names to be included in current Spring 
   * Data JPA Repository
   * 
   * @return a non empty array with finder names
   */
  String[] finders(); // No default => mandatory

}
