package org.springframework.roo.addon.finder.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks the annotated type as a Spring Data JPA repository that 
 * contains finders generated by Spring Roo. 
 * 
 * @author Juan Carlos García
 * @author Sergio Clares
 * @since 2.0
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface RooFinders {

  /**
   * The name of this annotation's attribute that specifies the finders
   */
  String FINDERS_ATTRIBUTE = "finders";

  /**
   * The array of {@link RooFinder} with the finders to be included in 
   * current Spring Data JPA Repository
   * 
   * @return a non empty array with one or more {@link RooFinder}
   */
  RooFinder[] finders(); // No default => mandatory

}
