[[command-index]]
Command Index
-------------

This appendix was automatically built from Roo 1.3.0.RELEASE [rev
770570e].

Commands are listed in alphabetic order, and are shown in monospaced
font with any mandatory options you must specify when using the command.
Most commands accept a large number of options, and all of the possible
options for each command are presented in this appendix.

[[command-index-add-on-commands]]
Add On Commands
---------------

Add On Commands are contained in
org.springframework.roo.addon.roobot.client.AddOnCommands.

[[command-index-addon-feedback-bundle]]
addon feedback bundle
~~~~~~~~~~~~~~~~~~~~~

Provide anonymous ratings and comments on a Spring Roo Add-on (your
feedback will be published publicly)

---------------------------------------------------
addon feedback bundle --bundleSymbolicName --rating
---------------------------------------------------

--bundleSymbolicName::
  The bundle symbolic name for the add-on of interest; default:
  '__NULL__' (mandatory)
--rating::
  How much did you like this add-on?; default: '__NULL__' (mandatory)
--comment::
  Your comments on this add-on eg "this is my comment!"; limit of 140
  characters; default: '__NULL__'

[[command-index-addon-info-bundle]]
addon info bundle
~~~~~~~~~~~~~~~~~

Provide information about a specific Spring Roo Add-on

--------------------------------------
addon info bundle --bundleSymbolicName
--------------------------------------

--bundleSymbolicName::
  The bundle symbolic name for the add-on of interest; default:
  '__NULL__' (mandatory)

[[command-index-addon-info-id]]
addon info id
~~~~~~~~~~~~~

Provide information about a specific Spring Roo Add-on

------------------------------
addon info id --searchResultId
------------------------------

--searchResultId::
  The bundle ID as presented via the addon list or addon search command;
  default: '__NULL__' (mandatory)

[[command-index-addon-install-bundle]]
addon install bundle
~~~~~~~~~~~~~~~~~~~~

Install Spring Roo Add-on

-----------------------------------------
addon install bundle --bundleSymbolicName
-----------------------------------------

--bundleSymbolicName::
  The bundle symbolic name for the add-on of interest; default:
  '__NULL__' (mandatory)

[[command-index-addon-install-id]]
addon install id
~~~~~~~~~~~~~~~~

Install Spring Roo Add-on

---------------------------------
addon install id --searchResultId
---------------------------------

--searchResultId::
  The bundle ID as presented via the addon list or addon search command;
  default: '__NULL__' (mandatory)

[[command-index-addon-list]]
addon list
~~~~~~~~~~

List all known Spring Roo Add-ons (up to the maximum number displayed on
a single page)

----------
addon list
----------

--refresh::
  Refresh the add-on index from the Internet; default if option present:
  'true'; default if option not present: 'false'
--linesPerResult::
  The maximum number of lines displayed per add-on; default: '2'
--maxResults::
  The maximum number of add-ons to list; default: '99'
--trustedOnly::
  Only display trusted add-ons in search results; default if option
  present: 'true'; default if option not present: 'false'
--communityOnly::
  Only display community provided add-ons in search results; default if
  option present: 'true'; default if option not present: 'false'
--compatibleOnly::
  Only display compatible add-ons in search results; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-addon-remove]]
addon remove
~~~~~~~~~~~~

Remove Spring Roo Add-on

---------------------------------
addon remove --bundleSymbolicName
---------------------------------

--bundleSymbolicName::
  The bundle symbolic name for the add-on of interest; default:
  '__NULL__' (mandatory)

[[command-index-addon-search]]
addon search
~~~~~~~~~~~~

Search all known Spring Roo Add-ons

------------
addon search
------------

--requiresDescription::
  A comma separated list of search terms; default: '*'
--refresh::
  Refresh the add-on index from the Internet; default if option present:
  'true'; default if option not present: 'false'
--linesPerResult::
  The maximum number of lines displayed per add-on; default: '2'
--maxResults::
  The maximum number of add-ons to list; default: '20'
--trustedOnly::
  Only display trusted add-ons in search results; default if option
  present: 'true'; default if option not present: 'false'
--compatibleOnly::
  Only display compatible add-ons in search results; default if option
  present: 'true'; default if option not present: 'false'
--communityOnly::
  Only display community provided add-ons in search results; default if
  option present: 'true'; default if option not present: 'false'
--requiresCommand::
  Only display add-ons in search results that offer this command;
  default: '__NULL__'

[[command-index-addon-upgrade-all]]
addon upgrade all
~~~~~~~~~~~~~~~~~

Upgrade all relevant Spring Roo Add-ons / Components for the current
stability level

-----------------
addon upgrade all
-----------------

This command does not accept any options.

[[command-index-addon-upgrade-available]]
addon upgrade available
~~~~~~~~~~~~~~~~~~~~~~~

List available Spring Roo Add-on / Component upgrades

-----------------------
addon upgrade available
-----------------------

--addonStabilityLevel::
  The stability level of add-ons or components which are presented for
  upgrading (default: ANY); default: '__NULL__'

[[command-index-addon-upgrade-bundle]]
addon upgrade bundle
~~~~~~~~~~~~~~~~~~~~

Upgrade a specific Spring Roo Add-on / Component

-----------------------------------------
addon upgrade bundle --bundleSymbolicName
-----------------------------------------

--bundleSymbolicName::
  The bundle symbolic name for the add-on to upgrade; default:
  '__NULL__' (mandatory)

[[command-index-addon-upgrade-id]]
addon upgrade id
~~~~~~~~~~~~~~~~

Upgrade a specific Spring Roo Add-on / Component from a search result ID

---------------------------------
addon upgrade id --searchResultId
---------------------------------

--searchResultId::
  The bundle ID as presented via the addon list or addon search command;
  default: '__NULL__' (mandatory)

[[command-index-addon-upgrade-settings]]
addon upgrade settings
~~~~~~~~~~~~~~~~~~~~~~

Settings for Add-on upgrade operations

----------------------
addon upgrade settings
----------------------

--addonStabilityLevel::
  The stability level of add-ons or components which are presented for
  upgrading; default: '__NULL__'

[[command-index-backup-commands]]
Backup Commands
---------------

Backup Commands are contained in
org.springframework.roo.addon.backup.BackupCommands.

[[command-index-backup]]
backup
~~~~~~

Backup your project to a zip file

------
backup
------

This command does not accept any options.

[[command-index-classpath-commands]]
Classpath Commands
------------------

Classpath Commands are contained in
org.springframework.roo.classpath.operations.ClasspathCommands.

[[command-index-class]]
class
~~~~~

Creates a new Java class source file in any project path

-------------
class --class
-------------

--class::
  The name of the class to create; default: '__NULL__' (mandatory)
--rooAnnotations::
  Whether the generated class should have common Roo annotations;
  default if option present: 'true'; default if option not present:
  'false'
--path::
  Source directory to create the class in; default:
  'FOCUSED|SRC_MAIN_JAVA'
--extends::
  The superclass (defaults to java.lang.Object); default if option not
  present: 'java.lang.Object'
--implements::
  The interface to implement; default: '__NULL__'
--abstract::
  Whether the generated class should be marked as abstract; default if
  option present: 'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-constructor]]
constructor
~~~~~~~~~~~

Creates a class constructor

-----------
constructor
-----------

--class::
  The name of the class to receive this constructor; default if option
  not present: '*'
--fields::
  The fields to include in the constructor. Multiple field names must be
  a double-quoted list separated by spaces

[[command-index-enum-constant]]
enum constant
~~~~~~~~~~~~~

Inserts a new enum constant into an enum

--------------------
enum constant --name
--------------------

--class::
  The name of the enum class to receive this field; default if option
  not present: '*'
--name::
  The name of the constant; default: '__NULL__' (mandatory)
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-enum-type]]
enum type
~~~~~~~~~

Creates a new Java enum source file in any project path

-----------------
enum type --class
-----------------

--class::
  The name of the enum to create; default: '__NULL__' (mandatory)
--path::
  Source directory to create the enum in; default:
  'FOCUSED|SRC_MAIN_JAVA'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-focus]]
focus
~~~~~

Changes focus to a different type

-------------
focus --class
-------------

--class::
  The type to focus on; default: '__NULL__' (mandatory)

[[command-index-interface]]
interface
~~~~~~~~~

Creates a new Java interface source file in any project path

-----------------
interface --class
-----------------

--class::
  The name of the interface to create; default: '__NULL__' (mandatory)
--path::
  Source directory to create the interface in; default:
  'FOCUSED|SRC_MAIN_JAVA'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-cloud-commands]]
Cloud Commands
--------------

Cloud Commands are contained in
org.springframework.roo.addon.cloud.CloudCommands.

[[command-index-cloud-setup]]
cloud setup
~~~~~~~~~~~

Setup Cloud Provider on Spring Roo Project

----------------------
cloud setup --provider
----------------------

--provider::
  Cloud Provider's Name; default: '__NULL__' (mandatory)
--configuration::
  Plugin Configuration. Add configuration by command like
  'key=value,key2=value2,key3=value3'; default: '__NULL__'

[[command-index-controller-commands]]
Controller Commands
-------------------

Controller Commands are contained in
org.springframework.roo.addon.web.mvc.controller.ControllerCommands.

[[command-index-controller-all]]
controller all
~~~~~~~~~~~~~~

Scaffold controllers for all project entities without an existing
controller - deprecated, use 'web mvc setup' + 'web mvc all' instead

------------------------
controller all --package
------------------------

--package::
  The package in which new controllers will be placed; default:
  '__NULL__' (mandatory)

[[command-index-controller-scaffold]]
controller scaffold
~~~~~~~~~~~~~~~~~~~

Create a new scaffold Controller (ie where we maintain CRUD
automatically) - deprecated, use 'web mvc scaffold' instead

---------------------------
controller scaffold --class
---------------------------

--class::
  The path and name of the controller object to be created; default:
  '__NULL__' (mandatory)
--entity::
  The name of the entity object which the controller exposes to the web
  tier; default if option not present: '*'
--path::
  The base path under which the controller listens for RESTful requests
  (defaults to the simple name of the form backing object); default:
  '__NULL__'
--disallowedOperations::
  A comma separated list of operations (only create, update, delete
  allowed) that should not be generated in the controller; default:
  '__NULL__'

[[command-index-web-mvc-all]]
web mvc all
~~~~~~~~~~~

Scaffold Spring MVC controllers for all project entities without an
existing controller

---------------------
web mvc all --package
---------------------

--package::
  The package in which new controllers will be placed; default:
  '__NULL__' (mandatory)

[[command-index-web-mvc-scaffold]]
web mvc scaffold
~~~~~~~~~~~~~~~~

Create a new scaffold Controller (ie where Roo maintains CRUD
functionality automatically)

------------------------
web mvc scaffold --class
------------------------

--class::
  The path and name of the controller object to be created; default:
  '__NULL__' (mandatory)
--backingType::
  The name of the form backing type which the controller exposes to the
  web tier; default if option not present: '*'
--path::
  The base path under which the controller listens for RESTful requests
  (defaults to the simple name of the form backing object); default:
  '__NULL__'
--disallowedOperations::
  A comma separated list of operations (only create, update, delete
  allowed) that should not be generated in the controller; default:
  '__NULL__'

[[command-index-creator-commands]]
Creator Commands
----------------

Creator Commands are contained in
org.springframework.roo.addon.creator.CreatorCommands.

[[command-index-addon-create-advanced]]
addon create advanced
~~~~~~~~~~~~~~~~~~~~~

Create a new advanced add-on for Spring Roo (commands + operations +
metadata + trigger annotation + dependencies)

---------------------------------------
addon create advanced --topLevelPackage
---------------------------------------

--topLevelPackage::
  The top level package of the new addon; default: '__NULL__'
  (mandatory)
--description::
  Description of your addon (surround text with double quotes); default:
  '__NULL__'
--projectName::
  Provide a custom project name (if not provided the top level package
  name will be used instead); default: '__NULL__'

[[command-index-addon-create-i18n]]
addon create i18n
~~~~~~~~~~~~~~~~~

Create a new Internationalization add-on for Spring Roo

------------------------------------------------------------
addon create i18n --topLevelPackage --locale --messageBundle
------------------------------------------------------------

--topLevelPackage::
  The top level package of the new addon; default: '__NULL__'
  (mandatory)
--locale::
  The locale abbreviation (ie: en, or more specific like en_AU, or
  de_DE); default: '__NULL__' (mandatory)
--messageBundle::
  Fully qualified path to the messages_xx.properties file; default:
  '__NULL__' (mandatory)
--language::
  The full name of the language (used as a label for the UI); default:
  '__NULL__'
--flagGraphic::
  Fully qualified path to flag xx.png file; default: '__NULL__'
--description::
  Description of your addon (surround text with double quotes); default:
  '__NULL__'
--projectName::
  Provide a custom project name (if not provided the top level package
  name will be used instead); default: '__NULL__'

[[command-index-addon-create-simple]]
addon create simple
~~~~~~~~~~~~~~~~~~~

Create a new simple add-on for Spring Roo (commands + operations)

-------------------------------------
addon create simple --topLevelPackage
-------------------------------------

--topLevelPackage::
  The top level package of the new addon; default: '__NULL__'
  (mandatory)
--description::
  Description of your addon (surround text with double quotes); default:
  '__NULL__'
--projectName::
  Provide a custom project name (if not provided the top level package
  name will be used instead); default: '__NULL__'

[[command-index-addon-create-wrapper]]
addon create wrapper
~~~~~~~~~~~~~~~~~~~~

Create a new add-on for Spring Roo which wraps a maven artifact to
create a OSGi compliant bundle

-------------------------------------------------------------------------------------------------
addon create wrapper --topLevelPackage --groupId --artifactId --version --vendorName --licenseUrl
-------------------------------------------------------------------------------------------------

--topLevelPackage::
  The top level package of the new wrapper bundle; default: '__NULL__'
  (mandatory)
--groupId::
  Dependency group id; default: '__NULL__' (mandatory)
--artifactId::
  Dependency artifact id); default: '__NULL__' (mandatory)
--version::
  Dependency version; default: '__NULL__' (mandatory)
--vendorName::
  Dependency vendor name); default: '__NULL__' (mandatory)
--licenseUrl::
  Dependency license URL; default: '__NULL__' (mandatory)
--docUrl::
  Dependency documentation URL; default: '__NULL__'
--description::
  Description of the bundle (use keywords with #-tags for better search
  integration); default: '__NULL__'
--projectName::
  Provide a custom project name (if not provided the top level package
  name will be used instead); default: '__NULL__'
--osgiImports::
  Contents of Import-Package in OSGi manifest; default: '__NULL__'

[[command-index-data-on-demand-commands]]
Data On Demand Commands
-----------------------

Data On Demand Commands are contained in
org.springframework.roo.addon.dod.DataOnDemandCommands.

[[command-index-dod]]
dod
~~~

Creates a new data on demand for the specified entity

---
dod
---

--entity::
  The entity which this data on demand class will create and modify as
  required; default if option not present: '*'
--class::
  The class which will be created to hold this data on demand provider
  (defaults to the entity name + 'DataOnDemand'); default: '__NULL__'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-dbre-commands]]
Dbre Commands
-------------

Dbre Commands are contained in
org.springframework.roo.addon.dbre.DbreCommands.

[[command-index-database-introspect]]
database introspect
~~~~~~~~~~~~~~~~~~~

Displays database metadata

----------------------------
database introspect --schema
----------------------------

--schema::
  The database schema names. Multiple schema names must be a
  double-quoted list separated by spaces; default: '__NULL__'
  (mandatory)
--file::
  The file to save the metadata to; default: '__NULL__'
--enableViews::
  Display database views; default if option present: 'true'; default if
  option not present: 'false'

[[command-index-database-reverse-engineer]]
database reverse engineer
~~~~~~~~~~~~~~~~~~~~~~~~~

Create and update entities based on database metadata

----------------------------------
database reverse engineer --schema
----------------------------------

--schema::
  The database schema names. Multiple schema names must be a
  double-quoted list separated by spaces; default: '__NULL__'
  (mandatory)
--package::
  The package in which new entities will be placed; default: '__NULL__'
--testAutomatically::
  Create automatic integration tests for entities; default if option
  present: 'true'; default if option not present: 'false'
--enableViews::
  Reverse engineer database views; default if option present: 'true';
  default if option not present: 'false'
--includeTables::
  The tables to include in reverse engineering. Multiple table names
  must be a double-quoted list separated by spaces
--excludeTables::
  The tables to exclude from reverse engineering. Multiple table names
  must be a double-quoted list separated by spaces
--includeNonPortableAttributes::
  Include non-portable JPA @Column attributes such as
  'columnDefinition'; default if option present: 'true'; default if
  option not present: 'false'
--disableVersionFields::
  Disable 'version' field; default if option present: 'true'; default if
  option not present: 'false'
--disableGeneratedIdentifiers::
  Disable identifier auto generation; default if option present: 'true';
  default if option not present: 'false'
--activeRecord::
  Generate CRUD active record methods for each entity; default: 'true'
--repository::
  Generate a repository for each entity; default if option present:
  'true'; default if option not present: 'false'
--service::
  Generate a service for each entity; default if option present: 'true';
  default if option not present: 'false'

[[command-index-embedded-commands]]
Embedded Commands
-----------------

Embedded Commands are contained in
org.springframework.roo.addon.web.mvc.embedded.EmbeddedCommands.

[[command-index-web-mvc-embed-document]]
web mvc embed document
~~~~~~~~~~~~~~~~~~~~~~

Embed a document for your WEB MVC application

----------------------------------------------
web mvc embed document --provider --documentId
----------------------------------------------

--provider::
  The id of the document; default: '__NULL__' (mandatory)
--documentId::
  The id of the document; default: '__NULL__' (mandatory)
--viewName::
  The name of the jspx view; default: '__NULL__'

[[command-index-web-mvc-embed-generic]]
web mvc embed generic
~~~~~~~~~~~~~~~~~~~~~

Embed media by URL into your WEB MVC application

---------------------------
web mvc embed generic --url
---------------------------

--url::
  The url of the source to be embedded; default: '__NULL__' (mandatory)
--viewName::
  The name of the jspx view; default: '__NULL__'

[[command-index-web-mvc-embed-map]]
web mvc embed map
~~~~~~~~~~~~~~~~~

Embed a map for your WEB MVC application

----------------------------
web mvc embed map --location
----------------------------

--location::
  The location of the map (ie "Sydney, Australia"); default: '__NULL__'
  (mandatory)
--viewName::
  The name of the jspx view; default: '__NULL__'

[[command-index-web-mvc-embed-photos]]
web mvc embed photos
~~~~~~~~~~~~~~~~~~~~

Embed a photo gallery for your WEB MVC application

--------------------------------------------------
web mvc embed photos --provider --userId --albumId
--------------------------------------------------

--provider::
  The provider of the photo gallery; default: '__NULL__' (mandatory)
--userId::
  The user id; default: '__NULL__' (mandatory)
--albumId::
  The album id; default: '__NULL__' (mandatory)
--viewName::
  The name of the jspx view; default: '__NULL__'

[[command-index-web-mvc-embed-stream-video]]
web mvc embed stream video
~~~~~~~~~~~~~~~~~~~~~~~~~~

Embed a video stream into your WEB MVC application

------------------------------------------------
web mvc embed stream video --provider --streamId
------------------------------------------------

--provider::
  The provider of the video stream; default: '__NULL__' (mandatory)
--streamId::
  The stream id; default: '__NULL__' (mandatory)
--viewName::
  The name of the jspx view; default: '__NULL__'

[[command-index-web-mvc-embed-twitter]]
web mvc embed twitter
~~~~~~~~~~~~~~~~~~~~~

Embed twitter messages into your WEB MVC application

----------------------------------
web mvc embed twitter --searchTerm
----------------------------------

--searchTerm::
  The search term to display results for; default: '__NULL__'
  (mandatory)
--viewName::
  The name of the jspx view; default: '__NULL__'

[[command-index-web-mvc-embed-video]]
web mvc embed video
~~~~~~~~~~~~~~~~~~~

Embed a video for your WEB MVC application

----------------------------------------
web mvc embed video --provider --videoId
----------------------------------------

--provider::
  The id of the video; default: '__NULL__' (mandatory)
--videoId::
  The id of the video; default: '__NULL__' (mandatory)
--viewName::
  The name of the jspx view; default: '__NULL__'

[[command-index-web-mvc-embed-wave]]
web mvc embed wave
~~~~~~~~~~~~~~~~~~

Embed Google wave integration for your WEB MVC application

---------------------------
web mvc embed wave --waveId
---------------------------

--waveId::
  The key of the wave; default: '__NULL__' (mandatory)
--viewName::
  The name of the jspx view; default: '__NULL__'

[[command-index-equals-commands]]
Equals Commands
---------------

Equals Commands are contained in
org.springframework.roo.addon.equals.EqualsCommands.

[[command-index-equals]]
equals
~~~~~~

Add equals and hashCode methods to a class

------
equals
------

--class::
  The name of the class; default if option not present: '*'
--appendSuper::
  Whether to call the super class equals and hashCode methods; default
  if option present: 'true'; default if option not present: 'false'
--excludeFields::
  The fields to exclude in the equals and hashcode methods. Multiple
  field names must be a double-quoted list separated by spaces

[[command-index-felix-delegator]]
Felix Delegator
---------------

Felix Delegator are contained in
org.springframework.roo.felix.FelixDelegator.

[[command-index-exit]]
exit
~~~~

Exits the shell

----
exit
----

This command does not accept any options.

[[command-index-osgi-framework-command]]
osgi framework command
~~~~~~~~~~~~~~~~~~~~~~

Passes a command directly through to the Felix shell infrastructure

----------------------
osgi framework command
----------------------

--[default]::
  The command to pass to Felix (WARNING: no validation or security
  checks are performed); default: 'help'

[[command-index-osgi-headers]]
osgi headers
~~~~~~~~~~~~

Display headers for a specific bundle

------------
osgi headers
------------

--bundleSymbolicName::
  Limit results to a specific bundle symbolic name; default: '__NULL__'

[[command-index-osgi-install]]
osgi install
~~~~~~~~~~~~

Installs a bundle JAR from a given URL

------------------
osgi install --url
------------------

--url::
  The URL to obtain the bundle from; default: '__NULL__' (mandatory)

[[command-index-osgi-log]]
osgi log
~~~~~~~~

Displays the OSGi log information

--------
osgi log
--------

--maximumEntries::
  The maximum number of log messages to display; default: '__NULL__'
--level::
  The minimum level of messages to display; default: '__NULL__'

[[command-index-osgi-obr-deploy]]
osgi obr deploy
~~~~~~~~~~~~~~~

Deploys a specific OSGi Bundle Repository (OBR) bundle

------------------------------------
osgi obr deploy --bundleSymbolicName
------------------------------------

--bundleSymbolicName::
  The specific bundle to deploy; default: '__NULL__' (mandatory)

[[command-index-osgi-obr-info]]
osgi obr info
~~~~~~~~~~~~~

Displays information on a specific OSGi Bundle Repository (OBR) bundle

----------------------------------
osgi obr info --bundleSymbolicName
----------------------------------

--bundleSymbolicName::
  The specific bundle to display information for; default: '__NULL__'
  (mandatory)

[[command-index-osgi-obr-list]]
osgi obr list
~~~~~~~~~~~~~

Lists all available bundles from the OSGi Bundle Repository (OBR) system

-------------
osgi obr list
-------------

--keywords::
  Keywords to locate; default: '__NULL__'

[[command-index-osgi-obr-start]]
osgi obr start
~~~~~~~~~~~~~~

Starts a specific OSGi Bundle Repository (OBR) bundle

-----------------------------------
osgi obr start --bundleSymbolicName
-----------------------------------

--bundleSymbolicName::
  The specific bundle to start; default: '__NULL__' (mandatory)

[[command-index-osgi-ps]]
osgi ps
~~~~~~~

Displays OSGi bundle information

-------
osgi ps
-------

--format::
  The format of bundle information; default: 'BUNDLE_NAME'

[[command-index-osgi-resolve]]
osgi resolve
~~~~~~~~~~~~

Resolves a specific bundle ID

---------------------------------
osgi resolve --bundleSymbolicName
---------------------------------

--bundleSymbolicName::
  The specific bundle to resolve; default: '__NULL__' (mandatory)

[[command-index-osgi-scr-config]]
osgi scr config
~~~~~~~~~~~~~~~

Lists the current SCR configuration

---------------
osgi scr config
---------------

This command does not accept any options.

[[command-index-osgi-scr-disable]]
osgi scr disable
~~~~~~~~~~~~~~~~

Disables a specific SCR-defined component

------------------------------
osgi scr disable --componentId
------------------------------

--componentId::
  The specific component identifier (use 'osgi scr list' to list
  component identifiers); default: '__NULL__' (mandatory)

[[command-index-osgi-scr-enable]]
osgi scr enable
~~~~~~~~~~~~~~~

Enables a specific SCR-defined component

-----------------------------
osgi scr enable --componentId
-----------------------------

--componentId::
  The specific component identifier (use 'osgi scr list' to list
  component identifiers); default: '__NULL__' (mandatory)

[[command-index-osgi-scr-info]]
osgi scr info
~~~~~~~~~~~~~

Lists information about a specific SCR-defined component

---------------------------
osgi scr info --componentId
---------------------------

--componentId::
  The specific component identifier (use 'osgi scr list' to list
  component identifiers); default: '__NULL__' (mandatory)

[[command-index-osgi-scr-list]]
osgi scr list
~~~~~~~~~~~~~

Lists all SCR-defined components

-------------
osgi scr list
-------------

--bundleId::
  Limit results to a specific bundle; default: '__NULL__'

[[command-index-osgi-start]]
osgi start
~~~~~~~~~~

Starts a bundle JAR from a given URL

----------------
osgi start --url
----------------

--url::
  The URL to obtain the bundle from; default: '__NULL__' (mandatory)

[[command-index-osgi-uninstall]]
osgi uninstall
~~~~~~~~~~~~~~

Uninstalls a specific bundle

-----------------------------------
osgi uninstall --bundleSymbolicName
-----------------------------------

--bundleSymbolicName::
  The specific bundle to uninstall; default: '__NULL__' (mandatory)

[[command-index-osgi-update]]
osgi update
~~~~~~~~~~~

Updates a specific bundle

--------------------------------
osgi update --bundleSymbolicName
--------------------------------

--bundleSymbolicName::
  The specific bundle to update ; default: '__NULL__' (mandatory)
--url::
  The URL to obtain the updated bundle from; default: '__NULL__'

[[command-index-field-commands]]
Field Commands
--------------

Field Commands are contained in
org.springframework.roo.classpath.operations.FieldCommands.

[[command-index-field-boolean]]
field boolean
~~~~~~~~~~~~~

Adds a private boolean field to an existing Java source file

-------------------------
field boolean --fieldName
-------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--assertFalse::
  Whether this value must assert false; default if option present:
  'true'; default if option not present: 'false'
--assertTrue::
  Whether this value must assert true; default if option present:
  'true'; default if option not present: 'false'
--column::
  The JPA @Column name; default: '__NULL__'
--value::
  Inserts an optional Spring @Value annotation with the given content;
  default: '__NULL__'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--primitive::
  Indicates to use a primitive type; default if option present: 'true';
  default if option not present: 'false'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-date]]
field date
~~~~~~~~~~

Adds a private date field to an existing Java source file

-----------------------------
field date --fieldName --type
-----------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--type::
  The Java type of the entity; default: '__NULL__' (mandatory)
--persistenceType::
  The type of persistent storage to be used; default: '__NULL__'
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--future::
  Whether this value must be in the future; default if option present:
  'true'; default if option not present: 'false'
--past::
  Whether this value must be in the past; default if option present:
  'true'; default if option not present: 'false'
--column::
  The JPA @Column name; default: '__NULL__'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--value::
  Inserts an optional Spring @Value annotation with the given content;
  default: '__NULL__'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'
--dateFormat::
  Indicates the style of the date format (ignored if
  dateTimeFormatPattern is specified); default: 'MEDIUM'
--timeFormat::
  Indicates the style of the time format (ignored if
  dateTimeFormatPattern is specified); default: 'NONE'
--dateTimeFormatPattern::
  Indicates a DateTime format pattern such as yyyy-MM-dd hh:mm:ss a;
  default: '__NULL__'

[[command-index-field-embedded]]
field embedded
~~~~~~~~~~~~~~

Adds a private @Embedded field to an existing Java source file

---------------------------------
field embedded --fieldName --type
---------------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--type::
  The Java type of the @Embeddable class; default: '__NULL__'
  (mandatory)
--class::
  The name of the @Entity class to receive this field; default if option
  not present: '*'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-enum]]
field enum
~~~~~~~~~~

Adds a private enum field to an existing Java source file

-----------------------------
field enum --fieldName --type
-----------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--type::
  The enum type of this field; default: '__NULL__' (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--column::
  The JPA @Column name; default: '__NULL__'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--enumType::
  The fetch semantics at a JPA level; default: '__NULL__'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-file]]
field file
~~~~~~~~~~

Adds a byte array field for storing uploaded file contents
(JSF-scaffolded UIs only)

------------------------------------
field file --fieldName --contentType
------------------------------------

--fieldName::
  The name of the file upload field to add; default: '__NULL__'
  (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--contentType::
  The content type of the file; default: '__NULL__' (mandatory)
--autoUpload::
  Whether the file is uploaded automatically when selected; default if
  option present: 'true'; default if option not present: 'false'
--column::
  The JPA @Column name; default: '__NULL__'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-list]]
field list
~~~~~~~~~~

Adds a private List field to an existing Java source file (eg the 'one'
side of a many-to-one)

-----------------------------
field list --fieldName --type
-----------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--type::
  The entity which will be contained within the Set; default: '__NULL__'
  (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--mappedBy::
  The field name on the referenced type which owns the relationship;
  default: '__NULL__'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--sizeMin::
  The minimum number of elements in the collection; default: '__NULL__'
--sizeMax::
  The maximum number of elements in the collection; default: '__NULL__'
--cardinality::
  The relationship cardinality at a JPA level; default: 'MANY_TO_MANY'
--fetch::
  The fetch semantics at a JPA level; default: '__NULL__'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-number]]
field number
~~~~~~~~~~~~

Adds a private numeric field to an existing Java source file

-------------------------------
field number --fieldName --type
-------------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--type::
  The Java type of the entity; default: '__NULL__' (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--decimalMin::
  The BigDecimal string-based representation of the minimum value;
  default: '__NULL__'
--decimalMax::
  The BigDecimal string based representation of the maximum value;
  default: '__NULL__'
--digitsInteger::
  Maximum number of integral digits accepted for this number; default:
  '__NULL__'
--digitsFraction::
  Maximum number of fractional digits accepted for this number; default:
  '__NULL__'
--min::
  The minimum value; default: '__NULL__'
--max::
  The maximum value; default: '__NULL__'
--column::
  The JPA @Column name; default: '__NULL__'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--value::
  Inserts an optional Spring @Value annotation with the given content;
  default: '__NULL__'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--primitive::
  Indicates to use a primitive type if possible; default if option
  present: 'true'; default if option not present: 'false'
--unique::
  Indicates whether to mark the field with a unique constraint; default
  if option present: 'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-other]]
field other
~~~~~~~~~~~

Inserts a private field into the specified file

------------------------------
field other --fieldName --type
------------------------------

--fieldName::
  The name of the field; default: '__NULL__' (mandatory)
--type::
  The Java type of this field; default: '__NULL__' (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--column::
  The JPA @Column name; default: '__NULL__'
--value::
  Inserts an optional Spring @Value annotation with the given content;
  default: '__NULL__'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-reference]]
field reference
~~~~~~~~~~~~~~~

Adds a private reference field to an existing Java source file (eg the
'many' side of a many-to-one)

----------------------------------
field reference --fieldName --type
----------------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--type::
  The Java type of the entity to reference; default: '__NULL__'
  (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--joinColumnName::
  The JPA @JoinColumn name; default: '__NULL__'
--referencedColumnName::
  The JPA @JoinColumn referencedColumnName; default: '__NULL__'
--cardinality::
  The relationship cardinality at a JPA level; default: 'MANY_TO_ONE'
--fetch::
  The fetch semantics at a JPA level; default: '__NULL__'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-set]]
field set
~~~~~~~~~

Adds a private Set field to an existing Java source file (eg the 'one'
side of a many-to-one)

----------------------------
field set --fieldName --type
----------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--type::
  The entity which will be contained within the Set; default: '__NULL__'
  (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--mappedBy::
  The field name on the referenced type which owns the relationship;
  default: '__NULL__'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--sizeMin::
  The minimum number of elements in the collection; default: '__NULL__'
--sizeMax::
  The maximum number of elements in the collection; default: '__NULL__'
--cardinality::
  The relationship cardinality at a JPA level; default: 'MANY_TO_MANY'
--fetch::
  The fetch semantics at a JPA level; default: '__NULL__'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-field-string]]
field string
~~~~~~~~~~~~

Adds a private string field to an existing Java source file

------------------------
field string --fieldName
------------------------

--fieldName::
  The name of the field to add; default: '__NULL__' (mandatory)
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--notNull::
  Whether this value cannot be null; default if option present: 'true';
  default if option not present: 'false'
--nullRequired::
  Whether this value must be null; default if option present: 'true';
  default if option not present: 'false'
--decimalMin::
  The BigDecimal string-based representation of the minimum value;
  default: '__NULL__'
--decimalMax::
  The BigDecimal string based representation of the maximum value;
  default: '__NULL__'
--sizeMin::
  The minimum string length; default: '__NULL__'
--sizeMax::
  The maximum string length; default: '__NULL__'
--regexp::
  The required regular expression pattern; default: '__NULL__'
--column::
  The JPA @Column name; default: '__NULL__'
--value::
  Inserts an optional Spring @Value annotation with the given content;
  default: '__NULL__'
--comment::
  An optional comment for JavaDocs; default: '__NULL__'
--transient::
  Indicates to mark the field as transient; default if option present:
  'true'; default if option not present: 'false'
--unique::
  Indicates whether to mark the field with a unique constraint; default
  if option present: 'true'; default if option not present: 'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'
--lob::
  Indicates that this field is a Large Object; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-finder-commands]]
Finder Commands
---------------

Finder Commands are contained in
org.springframework.roo.addon.finder.FinderCommands.

[[command-index-finder-add]]
finder add
~~~~~~~~~~

Install finders in the given target (must be an entity)

-----------------------
finder add --finderName
-----------------------

--class::
  The controller or entity for which the finders are generated; default
  if option not present: '*'
--finderName::
  The finder string as generated with the 'finder list' command;
  default: '__NULL__' (mandatory)

[[command-index-finder-list]]
finder list
~~~~~~~~~~~

List all finders for a given target (must be an entity)

-----------
finder list
-----------

--class::
  The controller or entity for which the finders are generated; default
  if option not present: '*'
--depth::
  The depth of attribute combinations to be generated for the finders;
  default: '1'
--filter::
  A comma separated list of strings that must be present in a filter to
  be included; default: '__NULL__'

[[command-index-help-commands]]
Help Commands
-------------

Help Commands are contained in
org.springframework.roo.felix.help.HelpCommands.

[[command-index-help]]
help
~~~~

Shows system help

----
help
----

--command::
  Command name to provide help for; default: '__NULL__'

[[command-index-reference-guide]]
reference guide
~~~~~~~~~~~~~~~

Writes the reference guide XML fragments (in DocBook format) into the
current working directory

---------------
reference guide
---------------

This command does not accept any options.

[[command-index-hint-commands]]
Hint Commands
-------------

Hint Commands are contained in
org.springframework.roo.classpath.operations.HintCommands.

[[command-index-hint]]
hint
~~~~

Provides step-by-step hints and context-sensitive guidance

----
hint
----

--topic::
  The topic for which advice should be provided

[[command-index-integration-test-commands]]
Integration Test Commands
-------------------------

Integration Test Commands are contained in
org.springframework.roo.addon.test.IntegrationTestCommands.

[[command-index-test-integration]]
test integration
~~~~~~~~~~~~~~~~

Creates a new integration test for the specified entity

----------------
test integration
----------------

--entity::
  The name of the entity to create an integration test for; default if
  option not present: '*'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'
--transactional::
  Indicates whether the created test cases should be run withing a
  Spring transaction; default: 'true'

[[command-index-test-mock]]
test mock
~~~~~~~~~

Creates a mock test for the specified entity

---------
test mock
---------

--entity::
  The name of the entity this mock test is targeting; default if option
  not present: '*'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-test-stub]]
test stub
~~~~~~~~~

Creates a test stub for the specified class

---------
test stub
---------

--class::
  The name of the class this mock test is targeting; default if option
  not present: '*'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-j-line-shell-component]]
J Line Shell Component
----------------------

J Line Shell Component are contained in
org.springframework.roo.shell.jline.osgi.JLineShellComponent.

[[command-index-asxfwd]]
*/
~~

End of block comment

--
*/
--

This command does not accept any options.

[[command-index-fwdasx]]
/*
~~

Start of block comment

--
/*
--

This command does not accept any options.

[[command-index-fwdfwd]]
//
~~

Inline comment markers (start of line only)

--
//
--

This command does not accept any options.

[[command-index-date]]
date
~~~~

Displays the local date and time

----
date
----

This command does not accept any options.

[[command-index-flash-test]]
flash test
~~~~~~~~~~

Tests message flashing

----------
flash test
----------

This command does not accept any options.

[[command-index-script]]
script
~~~~~~

Parses the specified resource file and executes its commands

-------------
script --file
-------------

--file::
  The file to locate and execute; default: '__NULL__' (mandatory)
--lineNumbers::
  Display line numbers when executing the script; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-system-properties]]
system properties
~~~~~~~~~~~~~~~~~

Shows the shell's properties

-----------------
system properties
-----------------

This command does not accept any options.

[[command-index-version]]
version
~~~~~~~

Displays shell version

-------
version
-------

--[default]::
  Special version flags; default: '__NULL__'

[[command-index-jms-commands]]
Jms Commands
------------

Jms Commands are contained in
org.springframework.roo.addon.jms.JmsCommands.

[[command-index-field-jms-template]]
field jms template
~~~~~~~~~~~~~~~~~~

Insert a JmsOperations field into an existing type

------------------
field jms template
------------------

--fieldName::
  The name of the field to add; default: 'jmsOperations'
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--async::
  Indicates if the injected method should be executed asynchronously;
  default if option present: 'true'; default if option not present:
  'false'

[[command-index-jms-listener-class]]
jms listener class
~~~~~~~~~~~~~~~~~~

Create an asynchronous JMS consumer

--------------------------
jms listener class --class
--------------------------

--class::
  The name of the class to create; default: '__NULL__' (mandatory)
--destinationName::
  The name of the destination; default: 'myDestination'
--destinationType::
  The type of the destination; default: 'QUEUE'

[[command-index-jms-setup]]
jms setup
~~~~~~~~~

Install a JMS provider into your project

--------------------
jms setup --provider
--------------------

--provider::
  The persistence provider to support; default: '__NULL__' (mandatory)
--destinationName::
  The name of the destination; default: 'myDestination'
--destinationType::
  The type of the destination; default: 'QUEUE'

[[command-index-jpa-commands]]
Jpa Commands
------------

Jpa Commands are contained in
org.springframework.roo.addon.jpa.JpaCommands.

[[command-index-database-properties-list]]
database properties list
~~~~~~~~~~~~~~~~~~~~~~~~

Shows database configuration details

------------------------
database properties list
------------------------

This command does not accept any options.

[[command-index-database-properties-remove]]
database properties remove
~~~~~~~~~~~~~~~~~~~~~~~~~~

Removes a particular database property

--------------------------------
database properties remove --key
--------------------------------

--key::
  The property key that should be removed; default: '__NULL__'
  (mandatory)

[[command-index-database-properties-set]]
database properties set
~~~~~~~~~~~~~~~~~~~~~~~

Changes a particular database property

-------------------------------------
database properties set --key --value
-------------------------------------

--key::
  The property key that should be changed; default: '__NULL__'
  (mandatory)
--value::
  The new vale for this property key; default: '__NULL__' (mandatory)

[[command-index-embeddable]]
embeddable
~~~~~~~~~~

Creates a new Java class source file with the JPA @Embeddable annotation
in SRC_MAIN_JAVA

------------------
embeddable --class
------------------

--class::
  The name of the class to create; default: '__NULL__' (mandatory)
--serializable::
  Whether the generated class should implement java.io.Serializable;
  default if option present: 'true'; default if option not present:
  'false'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-entity-jpa]]
entity jpa
~~~~~~~~~~

Creates a new JPA persistent entity in SRC_MAIN_JAVA

------------------
entity jpa --class
------------------

--class::
  Name of the entity to create; default: '__NULL__' (mandatory)
--extends::
  The superclass (defaults to java.lang.Object); default if option not
  present: 'java.lang.Object'
--implements::
  The interface to implement; default: '__NULL__'
--abstract::
  Whether the generated class should be marked as abstract; default if
  option present: 'true'; default if option not present: 'false'
--testAutomatically::
  Create automatic integration tests for this entity; default if option
  present: 'true'; default if option not present: 'false'
--table::
  The JPA table name to use for this entity; default: '__NULL__'
--schema::
  The JPA table schema name to use for this entity; default: '__NULL__'
--catalog::
  The JPA table catalog name to use for this entity; default: '__NULL__'
--identifierField::
  The JPA identifier field name to use for this entity; default:
  '__NULL__'
--identifierColumn::
  The JPA identifier field column to use for this entity; default:
  '__NULL__'
--identifierType::
  The data type that will be used for the JPA identifier field (defaults
  to java.lang.Long); default: 'java.lang.Long'
--versionField::
  The JPA version field name to use for this entity; default: '__NULL__'
--versionColumn::
  The JPA version field column to use for this entity; default:
  '__NULL__'
--versionType::
  The data type that will be used for the JPA version field (defaults to
  java.lang.Integer); default if option not present: 'java.lang.Integer'
--inheritanceType::
  The JPA @Inheritance value (apply to base class); default: '__NULL__'
--mappedSuperclass::
  Apply @MappedSuperclass for this entity; default if option present:
  'true'; default if option not present: 'false'
--equals::
  Whether the generated class should implement equals and hashCode
  methods; default if option present: 'true'; default if option not
  present: 'false'
--serializable::
  Whether the generated class should implement java.io.Serializable;
  default if option present: 'true'; default if option not present:
  'false'
--persistenceUnit::
  The persistence unit name to be used in the persistence.xml file;
  default: '__NULL__'
--transactionManager::
  The transaction manager name; default: '__NULL__'
--permitReservedWords::
  Indicates whether reserved words are ignored by Roo; default if option
  present: 'true'; default if option not present: 'false'
--entityName::
  The name used to refer to the entity in queries; default: '__NULL__'
--sequenceName::
  The name of the sequence for incrementing sequence-driven primary
  keys; default: '__NULL__'
--activeRecord::
  Generate CRUD active record methods for this entity; default: 'true'

[[command-index-jpa-setup]]
jpa setup
~~~~~~~~~

Install or updates a JPA persistence provider in your project

-------------------------------
jpa setup --provider --database
-------------------------------

--provider::
  The persistence provider to support; default: '__NULL__' (mandatory)
--database::
  The database to support; default: '__NULL__' (mandatory)
--applicationId::
  The Google App Engine application identifier to use; default if option
  not present: 'the project's name'
--jndiDataSource::
  The JNDI datasource to use; default: '__NULL__'
--hostName::
  The host name to use; default: '__NULL__'
--databaseName::
  The database name to use; default: '__NULL__'
--userName::
  The username to use; default: '__NULL__'
--password::
  The password to use; default: '__NULL__'
--transactionManager::
  The transaction manager name; default: '__NULL__'
--persistenceUnit::
  The persistence unit name to be used in the persistence.xml file;
  default: '__NULL__'

[[command-index-persistence-setup]]
persistence setup
~~~~~~~~~~~~~~~~~

Install or updates a JPA persistence provider in your project -
deprecated, use 'jpa setup' instead

---------------------------------------
persistence setup --provider --database
---------------------------------------

--provider::
  The persistence provider to support; default: '__NULL__' (mandatory)
--database::
  The database to support; default: '__NULL__' (mandatory)
--applicationId::
  The Google App Engine application identifier to use; default if option
  not present: 'the project's name'
--jndiDataSource::
  The JNDI datasource to use; default: '__NULL__'
--hostName::
  The host name to use; default: '__NULL__'
--databaseName::
  The database name to use; default: '__NULL__'
--userName::
  The username to use; default: '__NULL__'
--password::
  The password to use; default: '__NULL__'
--transactionManager::
  The transaction manager name; default: '__NULL__'
--persistenceUnit::
  The persistence unit name to be used in the persistence.xml file;
  default: '__NULL__'

[[command-index-jsf-commands]]
Jsf Commands
------------

Jsf Commands are contained in
org.springframework.roo.addon.jsf.JsfCommands.

[[command-index-web-jsf-all]]
web jsf all
~~~~~~~~~~~

Create JSF managed beans for all entities

---------------------
web jsf all --package
---------------------

--package::
  The package in which new JSF managed beans will be placed; default:
  '__NULL__' (mandatory)

[[command-index-web-jsf-media]]
web jsf media
~~~~~~~~~~~~~

Add a cross-browser generic player to embed multimedia content

-------------------
web jsf media --url
-------------------

--url::
  The url of the media source; default: '__NULL__' (mandatory)
--player::
  The name of the media player; default: '__NULL__'

[[command-index-web-jsf-scaffold]]
web jsf scaffold
~~~~~~~~~~~~~~~~

Create JSF managed bean for an entity

------------------------
web jsf scaffold --class
------------------------

--class::
  The path and name of the JSF managed bean to be created; default:
  '__NULL__' (mandatory)
--entity::
  The entity which this JSF managed bean class will create and modify as
  required; default if option not present: '*'
--beanName::
  The name of the managed bean to use in the 'name' attribute of the
  @ManagedBean annotation; default: '__NULL__'
--includeOnMenu::
  Include this entity on the generated JSF menu; default: 'true'

[[command-index-web-jsf-setup]]
web jsf setup
~~~~~~~~~~~~~

Set up JSF environment

-------------
web jsf setup
-------------

--implementation::
  The JSF implementation to use; default: '__NULL__'
--library::
  The JSF component library to use; default: '__NULL__'
--theme::
  The name of the theme; default: '__NULL__'

[[command-index-json-commands]]
Json Commands
-------------

Json Commands are contained in
org.springframework.roo.addon.json.JsonCommands.

[[command-index-json-add]]
json add
~~~~~~~~

Adds @RooJson annotation to target type

--------
json add
--------

--class::
  The java type to apply this annotation to; default if option not
  present: '*'
--rootName::
  The root name which should be used to wrap the JSON document; default:
  '__NULL__'
--deepSerialize::
  Indication if deep serialization should be enabled.; default if option
  present: 'true'; default if option not present: 'false'
--iso8601Dates::
  Indication if dates should be formatted according to ISO 8601; default
  if option present: 'true'; default if option not present: 'false'

[[command-index-json-all]]
json all
~~~~~~~~

Adds @RooJson annotation to all types annotated with @RooJavaBean

--------
json all
--------

--deepSerialize::
  Indication if deep serialization should be enabled; default if option
  present: 'true'; default if option not present: 'false'
--iso8601Dates::
  Indication if dates should be formatted according to ISO 8601; default
  if option present: 'true'; default if option not present: 'false'

[[command-index-jsp-commands]]
Jsp Commands
------------

Jsp Commands are contained in
org.springframework.roo.addon.web.mvc.jsp.JspCommands.

[[command-index-controller-class]]
controller class
~~~~~~~~~~~~~~~~

Create a new manual Controller (ie where you write the methods) -
deprecated, use 'web mvc controller' instead

------------------------
controller class --class
------------------------

--class::
  The path and name of the controller object to be created; default:
  '__NULL__' (mandatory)
--preferredMapping::
  Indicates a specific request mapping path for this controller (eg
  /foo/); default: '__NULL__'

[[command-index-web-mvc-controller]]
web mvc controller
~~~~~~~~~~~~~~~~~~

Create a new manual Controller (ie where you write the methods)

--------------------------
web mvc controller --class
--------------------------

--class::
  The path and name of the controller object to be created; default:
  '__NULL__' (mandatory)
--preferredMapping::
  Indicates a specific request mapping path for this controller (eg
  /foo/); default: '__NULL__'

[[command-index-web-mvc-install-language]]
web mvc install language
~~~~~~~~~~~~~~~~~~~~~~~~

Install new internationalization bundle for MVC scaffolded UI.

-------------------------------
web mvc install language --code
-------------------------------

--code::
  The language code for the desired bundle; default: '__NULL__'
  (mandatory)

[[command-index-web-mvc-install-view]]
web mvc install view
~~~~~~~~~~~~~~~~~~~~

Create a new static view.

----------------------------------------------
web mvc install view --path --viewName --title
----------------------------------------------

--path::
  The path the static view to create in (required, ie '/foo/blah');
  default: '__NULL__' (mandatory)
--viewName::
  The view name the mapping this view should adopt (required, ie
  'index'); default: '__NULL__' (mandatory)
--title::
  The title of the view; default: '__NULL__' (mandatory)

[[command-index-web-mvc-language]]
web mvc language
~~~~~~~~~~~~~~~~

Install new internationalization bundle for MVC scaffolded UI.

-----------------------
web mvc language --code
-----------------------

--code::
  The language code for the desired bundle; default: '__NULL__'
  (mandatory)

[[command-index-web-mvc-setup]]
web mvc setup
~~~~~~~~~~~~~

Setup a basic project structure for a Spring MVC / JSP application

-------------
web mvc setup
-------------

This command does not accept any options.

[[command-index-web-mvc-update-tags]]
web mvc update tags
~~~~~~~~~~~~~~~~~~~

Replace an existing application tagx library with the latest version
(use --backup option to backup your application first)

-------------------
web mvc update tags
-------------------

--backup::
  Backup your application before replacing your existing tag library;
  default if option present: 'true'; default if option not present:
  'false'

[[command-index-web-mvc-view]]
web mvc view
~~~~~~~~~~~~

Create a new static view.

--------------------------------------
web mvc view --path --viewName --title
--------------------------------------

--path::
  The path the static view to create in (required, ie '/foo/blah');
  default: '__NULL__' (mandatory)
--viewName::
  The view name the mapping this view should adopt (required, ie
  'index'); default: '__NULL__' (mandatory)
--title::
  The title of the view; default: '__NULL__' (mandatory)

[[command-index-logging-commands]]
Logging Commands
----------------

Logging Commands are contained in
org.springframework.roo.addon.logging.LoggingCommands.

[[command-index-logging-setup]]
logging setup
~~~~~~~~~~~~~

Configure logging in your project

---------------------
logging setup --level
---------------------

--level::
  The log level to configure; default: '__NULL__' (mandatory)
--package::
  The package to append the logging level to (all by default); default:
  '__NULL__'

[[command-index-mail-commands]]
Mail Commands
-------------

Mail Commands are contained in
org.springframework.roo.addon.email.MailCommands.

[[command-index-email-sender-setup]]
email sender setup
~~~~~~~~~~~~~~~~~~

Install a Spring JavaMailSender in your project

-------------------------------
email sender setup --hostServer
-------------------------------

--hostServer::
  The host server; default: '__NULL__' (mandatory)
--protocol::
  The protocol used by mail server; default: '__NULL__'
--port::
  The port used by mail server; default: '__NULL__'
--encoding::
  The encoding used for mail; default: '__NULL__'
--username::
  The mail account username; default: '__NULL__'
--password::
  The mail account password; default: '__NULL__'

[[command-index-email-template-setup]]
email template setup
~~~~~~~~~~~~~~~~~~~~

Configures a template for a SimpleMailMessage

--------------------
email template setup
--------------------

--from::
  The 'from' email (optional); default: '__NULL__'
--subject::
  The message subject (obtional); default: '__NULL__'

[[command-index-field-email-template]]
field email template
~~~~~~~~~~~~~~~~~~~~

Inserts a MailTemplate field into an existing type

--------------------
field email template
--------------------

--fieldName::
  The name of the field to add; default: 'mailTemplate'
--class::
  The name of the class to receive this field; default if option not
  present: '*'
--async::
  Indicates if the injected method should be executed asynchronously;
  default if option present: 'true'; default if option not present:
  'false'

[[command-index-maven-commands]]
Maven Commands
--------------

Maven Commands are contained in
org.springframework.roo.project.MavenCommands.

[[command-index-dependency-add]]
dependency add
~~~~~~~~~~~~~~

Adds a new dependency to the Maven project object model (POM)

-----------------------------------------------
dependency add --groupId --artifactId --version
-----------------------------------------------

--groupId::
  The group ID of the dependency; default: '__NULL__' (mandatory)
--artifactId::
  The artifact ID of the dependency; default: '__NULL__' (mandatory)
--version::
  The version of the dependency; default: '__NULL__' (mandatory)
--classifier::
  The classifier of the dependency; default: '__NULL__'
--scope::
  The scope of the dependency; default: '__NULL__'

[[command-index-dependency-remove]]
dependency remove
~~~~~~~~~~~~~~~~~

Removes an existing dependency from the Maven project object model (POM)

--------------------------------------------------
dependency remove --groupId --artifactId --version
--------------------------------------------------

--groupId::
  The group ID of the dependency; default: '__NULL__' (mandatory)
--artifactId::
  The artifact ID of the dependency; default: '__NULL__' (mandatory)
--version::
  The version of the dependency; default: '__NULL__' (mandatory)
--classifier::
  The classifier of the dependency; default: '__NULL__'

[[command-index-maven-repository-add]]
maven repository add
~~~~~~~~~~~~~~~~~~~~

Adds a new repository to the Maven project object model (POM)

-------------------------------
maven repository add --id --url
-------------------------------

--id::
  The ID of the repository; default: '__NULL__' (mandatory)
--name::
  The name of the repository; default: '__NULL__'
--url::
  The URL of the repository; default: '__NULL__' (mandatory)

[[command-index-maven-repository-remove]]
maven repository remove
~~~~~~~~~~~~~~~~~~~~~~~

Removes an existing repository from the Maven project object model (POM)

----------------------------------
maven repository remove --id --url
----------------------------------

--id::
  The ID of the repository; default: '__NULL__' (mandatory)
--url::
  The URL of the repository; default: '__NULL__' (mandatory)

[[command-index-module-create]]
module create
~~~~~~~~~~~~~

Creates a new Maven module

--------------------------------------------
module create --moduleName --topLevelPackage
--------------------------------------------

--moduleName::
  The name of the module; default: '__NULL__' (mandatory)
--topLevelPackage::
  The uppermost package name (this becomes the <groupId> in Maven and
  also the '~' value when using Roo's shell); default: '__NULL__'
  (mandatory)
--java::
  Forces a particular major version of Java to be used (will be
  auto-detected if unspecified; specify 6 or 7 only); default:
  '__NULL__'
--parent::
  The Maven coordinates of the parent POM, in the form
  "groupId:artifactId:version"; default: '__NULL__'
--packaging::
  The Maven packaging of this module; default if option not present:
  'jar'
--artifactId::
  The artifact ID of this module (defaults to moduleName if not
  specified); default: '__NULL__'

[[command-index-module-focus]]
module focus
~~~~~~~~~~~~

Changes focus to a different project module

-------------------------
module focus --moduleName
-------------------------

--moduleName::
  The module to focus on; default: '__NULL__' (mandatory)

[[command-index-perform-assembly]]
perform assembly
~~~~~~~~~~~~~~~~

Executes the assembly goal via Maven

----------------
perform assembly
----------------

This command does not accept any options.

[[command-index-perform-clean]]
perform clean
~~~~~~~~~~~~~

Executes a full clean (including Eclipse files) via Maven

-------------
perform clean
-------------

This command does not accept any options.

[[command-index-perform-command]]
perform command
~~~~~~~~~~~~~~~

Executes a user-specified Maven command

------------------------------
perform command --mavenCommand
------------------------------

--mavenCommand::
  User-specified Maven command (eg test:test); default: '__NULL__'
  (mandatory)

[[command-index-perform-eclipse]]
perform eclipse
~~~~~~~~~~~~~~~

Sets up Eclipse configuration via Maven (only necessary if you have not
installed the m2eclipse plugin in Eclipse)

---------------
perform eclipse
---------------

This command does not accept any options.

[[command-index-perform-package]]
perform package
~~~~~~~~~~~~~~~

Packages the application using Maven, but does not execute any tests

---------------
perform package
---------------

This command does not accept any options.

[[command-index-perform-tests]]
perform tests
~~~~~~~~~~~~~

Executes the tests via Maven

-------------
perform tests
-------------

This command does not accept any options.

[[command-index-project]]
project
~~~~~~~

Creates a new Maven project

-------------------------
project --topLevelPackage
-------------------------

--topLevelPackage::
  The uppermost package name (this becomes the <groupId> in Maven and
  also the '~' value when using Roo's shell); default: '__NULL__'
  (mandatory)
--projectName::
  The name of the project (last segment of package name used as
  default); default: '__NULL__'
--java::
  Forces a particular major version of Java to be used (will be
  auto-detected if unspecified; specify 5 or 6 or 7 only); default:
  '__NULL__'
--parent::
  The Maven coordinates of the parent POM, in the form
  "groupId:artifactId:version"; default: '__NULL__'
--packaging::
  The Maven packaging of this project; default if option not present:
  'jar'

[[command-index-metadata-commands]]
Metadata Commands
-----------------

Metadata Commands are contained in
org.springframework.roo.classpath.MetadataCommands.

[[command-index-metadata-cache]]
metadata cache
~~~~~~~~~~~~~~

Shows detailed metadata for the indicated type

--------------------------------
metadata cache --maximumCapacity
--------------------------------

--maximumCapacity::
  The maximum number of metadata items to cache; default: '__NULL__'
  (mandatory)

[[command-index-metadata-for-id]]
metadata for id
~~~~~~~~~~~~~~~

Shows detailed information about the metadata item

----------------------------
metadata for id --metadataId
----------------------------

--metadataId::
  The metadata ID (should start with MID:); default: '__NULL__'
  (mandatory)

[[command-index-metadata-for-module]]
metadata for module
~~~~~~~~~~~~~~~~~~~

Shows the ProjectMetadata for the indicated project module

-------------------
metadata for module
-------------------

--module::
  The module for which to retrieve the metadata (defaults to the focused
  module); default: '__NULL__'

[[command-index-metadata-for-type]]
metadata for type
~~~~~~~~~~~~~~~~~

Shows detailed metadata for the indicated type

------------------------
metadata for type --type
------------------------

--type::
  The Java type for which to display metadata; default: '__NULL__'
  (mandatory)

[[command-index-metadata-status]]
metadata status
~~~~~~~~~~~~~~~

Shows metadata statistics

---------------
metadata status
---------------

This command does not accept any options.

[[command-index-metadata-trace]]
metadata trace
~~~~~~~~~~~~~~

Traces metadata event delivery notifications

----------------------
metadata trace --level
----------------------

--level::
  The verbosity of notifications (0=none, 1=some, 2=all); default:
  '__NULL__' (mandatory)

[[command-index-mongo-commands]]
Mongo Commands
--------------

Mongo Commands are contained in
org.springframework.roo.addon.layers.repository.mongo.MongoCommands.

[[command-index-entity-mongo]]
entity mongo
~~~~~~~~~~~~

Creates a domain entity which can be backed by a MongoDB repository

--------------------
entity mongo --class
--------------------

--class::
  Implementation class for the specified interface; default: '__NULL__'
  (mandatory)
--identifierType::
  The ID type to be used for this domain type (defaults to BigInteger);
  default: '__NULL__'
--testAutomatically::
  Create automatic integration tests for this entity; default if option
  present: 'true'; default if option not present: 'false'

[[command-index-mongo-setup]]
mongo setup
~~~~~~~~~~~

Configures the project for MongoDB peristence.

-----------
mongo setup
-----------

--username::
  Username for accessing the database (defaults to ''); default:
  '__NULL__'
--password::
  Password for accessing the database (defaults to ''); default:
  '__NULL__'
--databaseName::
  Name of the database (defaults to project name); default: '__NULL__'
--port::
  Port for the database (defaults to '27017'); default: '__NULL__'
--host::
  Host for the database (defaults to '127.0.0.1'); default: '__NULL__'
--cloudFoundry::
  Deploy to CloudFoundry (defaults to 'false'); default if option
  present: 'true'; default if option not present: 'false'

[[command-index-repository-mongo]]
repository mongo
~~~~~~~~~~~~~~~~

Adds @RooMongoRepository annotation to target type

----------------------------
repository mongo --interface
----------------------------

--interface::
  The java interface to apply this annotation to; default: '__NULL__'
  (mandatory)
--entity::
  The domain entity this repository should expose; default if option not
  present: '*'

[[command-index-os-commands]]
Os Commands
-----------

Os Commands are contained in
org.springframework.roo.addon.oscommands.OsCommands.

[[command-index-!]]
!
~

Allows execution of operating system (OS) commands.

-
!
-

--command::
  The command to execute; default: ''

[[command-index-pgp-commands]]
Pgp Commands
------------

Pgp Commands are contained in
org.springframework.roo.felix.pgp.PgpCommands.

[[command-index-pgp-automatic-trust]]
pgp automatic trust
~~~~~~~~~~~~~~~~~~~

Indicates to automatically trust all keys encountered until the command
is invoked again

-------------------
pgp automatic trust
-------------------

This command does not accept any options.

[[command-index-pgp-key-view]]
pgp key view
~~~~~~~~~~~~

Downloads a remote key and displays it to the user (does not change any
trusts)

--------------------
pgp key view --keyId
--------------------

--keyId::
  The key ID to view (eg 00B5050F or 0x00B5050F); default: '__NULL__'
  (mandatory)

[[command-index-pgp-list-trusted-keys]]
pgp list trusted keys
~~~~~~~~~~~~~~~~~~~~~

Lists the keys you currently trust and have not been revoked at the time
last downloaded from a public key server

---------------------
pgp list trusted keys
---------------------

This command does not accept any options.

[[command-index-pgp-refresh-all]]
pgp refresh all
~~~~~~~~~~~~~~~

Refreshes all keys from public key servers

---------------
pgp refresh all
---------------

This command does not accept any options.

[[command-index-pgp-status]]
pgp status
~~~~~~~~~~

Displays the status of the PGP environment

----------
pgp status
----------

This command does not accept any options.

[[command-index-pgp-trust]]
pgp trust
~~~~~~~~~

Grants trust to a particular key ID

-----------------
pgp trust --keyId
-----------------

--keyId::
  The key ID to trust (eg 00B5050F or 0x00B5050F); default: '__NULL__'
  (mandatory)

[[command-index-pgp-untrust]]
pgp untrust
~~~~~~~~~~~

Revokes your trust for a particular key ID

-------------------
pgp untrust --keyId
-------------------

--keyId::
  The key ID to remove trust from (eg 00B5050F or 0x00B5050F); default:
  '__NULL__' (mandatory)

[[command-index-process-manager-commands]]
Process Manager Commands
------------------------

Process Manager Commands are contained in
org.springframework.roo.process.manager.ProcessManagerCommands.

[[command-index-development-mode]]
development mode
~~~~~~~~~~~~~~~~

Switches the system into development mode (greater diagnostic
information)

----------------
development mode
----------------

--enabled::
  Activates development mode; default: 'true'

[[command-index-poll-now]]
poll now
~~~~~~~~

Perform a manual file system poll

--------
poll now
--------

This command does not accept any options.

[[command-index-poll-speed]]
poll speed
~~~~~~~~~~

Changes the file system polling speed

---------------
poll speed --ms
---------------

--ms::
  The number of milliseconds between each poll; default: '__NULL__'
  (mandatory)

[[command-index-poll-status]]
poll status
~~~~~~~~~~~

Display file system polling information

-----------
poll status
-----------

This command does not accept any options.

[[command-index-process-manager-diagnostics-listener]]
Process Manager Diagnostics Listener
------------------------------------

Process Manager Diagnostics Listener are contained in
org.springframework.roo.process.manager.internal.ProcessManagerDiagnosticsListener.

[[command-index-process-manager-debug]]
process manager debug
~~~~~~~~~~~~~~~~~~~~~

Indicates if process manager debugging is desired

---------------------
process manager debug
---------------------

--enabled::
  Activates debug mode; default: 'true'

[[command-index-prop-file-commands]]
Prop File Commands
------------------

Prop File Commands are contained in
org.springframework.roo.addon.propfiles.PropFileCommands.

[[command-index-properties-list]]
properties list
~~~~~~~~~~~~~~~

Shows the details of a particular properties file

-----------------------------
properties list --name --path
-----------------------------

--name::
  Property file name (including .properties suffix); default: '__NULL__'
  (mandatory)
--path::
  Source path to property file; default: '__NULL__' (mandatory)

[[command-index-properties-remove]]
properties remove
~~~~~~~~~~~~~~~~~

Removes a particular properties file property

-------------------------------------
properties remove --name --path --key
-------------------------------------

--name::
  Property file name (including .properties suffix); default: '__NULL__'
  (mandatory)
--path::
  Source path to property file; default: '__NULL__' (mandatory)
--key::
  The property key that should be removed; default: '__NULL__'
  (mandatory)

[[command-index-properties-set]]
properties set
~~~~~~~~~~~~~~

Changes a particular properties file property

------------------------------------------
properties set --name --path --key --value
------------------------------------------

--name::
  Property file name (including .properties suffix); default: '__NULL__'
  (mandatory)
--path::
  Source path to property file; default: '__NULL__' (mandatory)
--key::
  The property key that should be changed; default: '__NULL__'
  (mandatory)
--value::
  The new vale for this property key; default: '__NULL__' (mandatory)

[[command-index-proxy-configuration-commands]]
Proxy Configuration Commands
----------------------------

Proxy Configuration Commands are contained in
org.springframework.roo.url.stream.jdk.ProxyConfigurationCommands.

[[command-index-proxy-configuration]]
proxy configuration
~~~~~~~~~~~~~~~~~~~

Shows the proxy server configuration

-------------------
proxy configuration
-------------------

This command does not accept any options.

[[command-index-repository-jpa-commands]]
Repository Jpa Commands
-----------------------

Repository Jpa Commands are contained in
org.springframework.roo.addon.layers.repository.jpa.RepositoryJpaCommands.

[[command-index-repository-jpa]]
repository jpa
~~~~~~~~~~~~~~

Adds @RooJpaRepository annotation to target type

--------------------------
repository jpa --interface
--------------------------

--interface::
  The java interface to apply this annotation to; default: '__NULL__'
  (mandatory)
--entity::
  The domain entity this repository should expose; default if option not
  present: '*'

[[command-index-security-commands]]
Security Commands
-----------------

Security Commands are contained in
org.springframework.roo.addon.security.SecurityCommands.

[[command-index-permissionevaluator]]
permissionEvaluator
~~~~~~~~~~~~~~~~~~~

Create a permission evaluator

-----------------------------
permissionEvaluator --package
-----------------------------

--package::
  The package to add the permission evaluator to; default: '__NULL__'
  (mandatory)

[[command-index-security-setup]]
security setup
~~~~~~~~~~~~~~

Install Spring Security into your project

--------------
security setup
--------------

This command does not accept any options.

[[command-index-selenium-commands]]
Selenium Commands
-----------------

Selenium Commands are contained in
org.springframework.roo.addon.web.selenium.SeleniumCommands.

[[command-index-selenium-test]]
selenium test
~~~~~~~~~~~~~

Creates a new Selenium test for a particular controller

--------------------------
selenium test --controller
--------------------------

--controller::
  Controller to create a Selenium test for; default: '__NULL__'
  (mandatory)
--name::
  Name of the test; default: '__NULL__'
--serverUrl::
  URL of the server where the web application is available, including
  protocol, port and hostname; default: 'http://localhost:8080/'

[[command-index-service-commands]]
Service Commands
----------------

Service Commands are contained in
org.springframework.roo.addon.layers.service.ServiceCommands.

[[command-index-service-all]]
service all
~~~~~~~~~~~

Adds @RooService annotation to all entities

------------------------------
service all --interfacePackage
------------------------------

--interfacePackage::
  The java interface package; default: '__NULL__' (mandatory)
--classPackage::
  The java package of the implementation classes for the interfaces;
  default: '__NULL__'
--useXmlConfiguration::
  When true, Spring Roo will configure services using XML. This is the
  default behavior for services using GAE; default: '__NULL__'

[[command-index-service-secure-all]]
service secure all
~~~~~~~~~~~~~~~~~~

Adds @RooService annotation to all entities with options for
authentication, authorization, and a permission evaluator

-------------------------------------
service secure all --interfacePackage
-------------------------------------

--interfacePackage::
  The java interface package; default: '__NULL__' (mandatory)
--classPackage::
  The java package of the implementation classes for the interfaces;
  default: '__NULL__'
--requireAuthentication::
  Whether or not users must be authenticated to use the service; default
  if option present: 'true'; default if option not present: 'false'
--authorizedRole::
  The role authorized the use the methods in the service (additional
  roles can be added after creation); default: '__NULL__'
--usePermissionEvaluator::
  Whether or not to use a PermissionEvaluator; default if option
  present: 'true'; default if option not present: 'false'
--useXmlConfiguration::
  When true, Spring Roo will configure services using XML.; default:
  '__NULL__'

[[command-index-service-secure-type]]
service secure type
~~~~~~~~~~~~~~~~~~~

Adds @RooService annotation to target type with options for
authentication, authorization, and a permission evaluator

-------------------------------
service secure type --interface
-------------------------------

--interface::
  The java interface to apply this annotation to; default: '__NULL__'
  (mandatory)
--class::
  Implementation class for the specified interface; default: '__NULL__'
--entity::
  The domain entity this service should expose; default if option not
  present: '*'
--requireAuthentication::
  Whether or not users must be authenticated to use the service; default
  if option present: 'ture'; default if option not present: 'false'
--authorizedRoles::
  The role authorized the use the methods in the service; default:
  '__NULL__'
--usePermissionEvaluator::
  Whether or not to use a PermissionEvaluator; default if option
  present: 'true'; default if option not present: 'false'
--useXmlConfiguration::
  When true, Spring Roo will configure services using XML.; default:
  '__NULL__'

[[command-index-service-type]]
service type
~~~~~~~~~~~~

Adds @RooService annotation to target type

------------------------
service type --interface
------------------------

--interface::
  The java interface to apply this annotation to; default: '__NULL__'
  (mandatory)
--class::
  Implementation class for the specified interface; default: '__NULL__'
--entity::
  The domain entity this service should expose; default if option not
  present: '*'
--useXmlConfiguration::
  When true, Spring Roo will configure services using XML.; default:
  '__NULL__'

[[command-index-solr-commands]]
Solr Commands
-------------

Solr Commands are contained in
org.springframework.roo.addon.solr.SolrCommands.

[[command-index-solr-add]]
solr add
~~~~~~~~

Make target type searchable

--------
solr add
--------

--class::
  The type to be made searchable; default if option not present: '*'

[[command-index-solr-all]]
solr all
~~~~~~~~

Make all eligible project types searchable

--------
solr all
--------

This command does not accept any options.

[[command-index-solr-setup]]
solr setup
~~~~~~~~~~

Install support for Solr search integration

----------
solr setup
----------

--searchServerUrl::
  The URL of the Solr search server; default:
  'http://localhost:8983/solr'

[[command-index-tailor-commands]]
Tailor Commands
---------------

Tailor Commands are contained in
org.springframework.roo.addon.tailor.TailorCommands.

[[command-index-tailor-activate]]
tailor activate
~~~~~~~~~~~~~~~

Activate a tailor configuration.

----------------------
tailor activate --name
----------------------

--name::
  The name of the tailor configuration; default: '__NULL__' (mandatory)

[[command-index-tailor-deactivate]]
tailor deactivate
~~~~~~~~~~~~~~~~~

Deactivate the tailor.

-----------------
tailor deactivate
-----------------

This command does not accept any options.

[[command-index-tailor-list]]
tailor list
~~~~~~~~~~~

List available tailor configurations.

-----------
tailor list
-----------

This command does not accept any options.

[[command-index-uaa-commands]]
Uaa Commands
------------

Uaa Commands are contained in org.springframework.roo.uaa.UaaCommands.

[[command-index-download-accept-terms-of-use]]
download accept terms of use
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Accepts the Spring User Agent Analysis (UAA) Terms of Use

----------------------------
download accept terms of use
----------------------------

This command does not accept any options.

[[command-index-download-privacy-level]]
download privacy level
~~~~~~~~~~~~~~~~~~~~~~

Changes the Spring User Agent Analysis (UAA) privacy level

-------------------------------------
download privacy level --privacyLevel
-------------------------------------

--privacyLevel::
  The new UAA privacy level to use; default: '__NULL__' (mandatory)

[[command-index-download-reject-terms-of-use]]
download reject terms of use
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Rejects the Spring User Agent Analysis (UAA) Terms of Use

----------------------------
download reject terms of use
----------------------------

This command does not accept any options.

[[command-index-download-status]]
download status
~~~~~~~~~~~~~~~

Provides a summary of the Spring User Agent Analysis (UAA) status and
commands

---------------
download status
---------------

This command does not accept any options.

[[command-index-download-view]]
download view
~~~~~~~~~~~~~

Displays the Spring User Agent Analysis (UAA) header content in plain
text

-------------
download view
-------------

--file::
  The file to save the UAA JSON content to; default: '__NULL__'

[[command-index-web-finder-commands]]
Web Finder Commands
-------------------

Web Finder Commands are contained in
org.springframework.roo.addon.web.mvc.controller.finder.WebFinderCommands.

[[command-index-web-mvc-finder-add]]
web mvc finder add
~~~~~~~~~~~~~~~~~~

Adds @RooWebFinder annotation to MVC controller type

------------------------------------
web mvc finder add --formBackingType
------------------------------------

--formBackingType::
  The finder-enabled type; default: '__NULL__' (mandatory)
--class::
  The controller java type to apply this annotation to; default if
  option not present: '*'

[[command-index-web-mvc-finder-all]]
web mvc finder all
~~~~~~~~~~~~~~~~~~

Adds @RooWebFinder annotation to existing MVC controllers

------------------
web mvc finder all
------------------

This command does not accept any options.

[[command-index-web-flow-commands]]
Web Flow Commands
-----------------

Web Flow Commands are contained in
org.springframework.roo.addon.web.flow.WebFlowCommands.

[[command-index-web-flow]]
web flow
~~~~~~~~

Install Spring Web Flow configuration artifacts into your project

--------
web flow
--------

--flowName::
  The name for your web flow; default: '__NULL__'

[[command-index-web-json-commands]]
Web Json Commands
-----------------

Web Json Commands are contained in
org.springframework.roo.addon.web.mvc.controller.json.WebJsonCommands.

[[command-index-web-mvc-json-add]]
web mvc json add
~~~~~~~~~~~~~~~~

Adds @RooJson annotation to target type

-----------------------------
web mvc json add --jsonObject
-----------------------------

--jsonObject::
  The JSON-enabled object which backs this Spring MVC controller.;
  default: '__NULL__' (mandatory)
--class::
  The java type to apply this annotation to; default if option not
  present: '*'

[[command-index-web-mvc-json-all]]
web mvc json all
~~~~~~~~~~~~~~~~

Adds or creates MVC controllers annotated with @RooWebJson annotation

----------------
web mvc json all
----------------

--package::
  The package in which new controllers will be placed; default:
  '__NULL__'

[[command-index-web-mvc-json-setup]]
web mvc json setup
~~~~~~~~~~~~~~~~~~

Set up Spring MVC to support JSON

------------------
web mvc json setup
------------------

This command does not accept any options.
