// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
package __TOP_LEVEL_PACKAGE__.__SEGMENT_PACKAGE__;

import com.google.gwt.event.shared.EventBus;
import com.google.inject.Inject;
import __TOP_LEVEL_PACKAGE__.client.managed.request.ApplicationRequestFactory;
import __TOP_LEVEL_PACKAGE__.client.scaffold.ScaffoldDesktopShell;
__GAE_IMPORT__
public class GaeHelper {

	@Inject
	public GaeHelper(ScaffoldDesktopShell shell, ApplicationRequestFactory requestFactory, EventBus eventBus) {
		__GAE_HOOKUP__
	}
}