package org.springframework.roo.addon.layers.service.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation indicates that annotated interface is a Service generated by
 * Spring Roo
 * 
 * @author Stefan Schmidt
 * @author Andrew Swan
 * @author Juan Carlos García
 * @since 1.2.0
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface RooService {

  /**
   * The name of this annotation's "entity" attribute
   */
  String ENTITY_ATTRIBUTE = "entity";

  /**
   * Returns the domain type managed by this service
   * 
   * @return a non-<code>null</code> class
   */
  Class<?> entity();

}
