package org.springframework.roo.addon.layers.service.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation indicates that annotated class is the implementation of a
 * Service interface generated by Spring Roo
 * 
 * @author Juan Carlos García
 * @since 2.0
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface RooServiceImpl {

  /**
   * The name of this annotation's "service" attribute
   */
  String SERVICE_ATTRIBUTE = "service";

  /**
   * Returns the service implemented by current class
   * 
   * @return a non-<code>null</code> class
   */
  Class<?> service();

}
